### ISSUE TITLE
Introduce packaged deployment plans

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/clarinet#1059]
Proposal: we introduce a new command that would generate a more portable plan.
Clarinet would keep using the current yaml format, but we'd be introducing a new version, generated from something like
```bash
$ clarinet deployment package /path/to/plan
```

A packaged deployment plan is a json file that looks a lot like a deployment plan, but instead of this
```yaml
id: 0
name: Devnet deployment
network: devnet
stacks-node: "http://localhost:20443"
bitcoin-node: "http://devnet:devnet@localhost:18443"
plan:
  batches:
    - id: 0
      transactions:
        - contract-publish:
            contract-name: hk-cursor-v1
            expected-sender: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM
            cost: 38790
            path: contracts/deps/hk-cursor-v1.clar
            anchor-block-only: true
            clarity-version: 2
      epoch: "2.4"
    - id: 1
      transactions:
        - contract-call:
            contract-id: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.wormhole-core-v1
            expected-sender: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM
            method: update-guardians-set
            parameters:
              - 0x00
              - '(list 1 2 3 4 5)
            cost: 5960
```

to something like this:

```json
{
  "id": 0,
  "name": "Devnet deployment",
  "network": "devnet",
  "stacks-node": "http://localhost:20443",
  "bitcoin-node": "http://devnet:devnet@localhost:18443",
  "plan": {
    "batches": [
      {
        "id": 0,
        "epoch": "2.4",
        "transactions": [
          "contract_publish": {
            "contract_name": "hk-cursor-v1",
            "expected_sender": "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM",
            "cost": 38790,
            "content": <BASE64EncodedContract>,
            "anchor_block_only": true,
            "clarity_version": 2
          }
        ]
      },
      {
        "id": 1,
        "epoch": "2.4",
        "transactions": [
          "contract_call": {
            "contract_id": "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.wormhole-core-v1",
            "expected_sender": "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM",
            "method": "update-guardians-set",
            "parameters": [
              "0x00",
              "(list 1 2 3 4 5)"
            ],
            "cost": 5960
          }
        ]
      }
    ]
  }
}
```

With an additional flag, we could also append the network settings.
