### ISSUE TITLE
Confusing NoSuchContract error when the epoch specified is the problem

### ISSUE THREAD

**Issue by pradel** [hirosystems/clarinet#1097]
**Describe the bug**

Write any clarity code using the `SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.amm-swap-pool-v1-1` contract and a 2.1 epoch gives you an `error: NoSuchContract("SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.amm-swap-pool-v1-1")` error. The error is confusing as the contract is added as a requirement but the epoch is wrong, it took me some time to understand and changing the epoch to `2.4` solved the issue.

Clarinet.toml:
```
[[project.requirements]]
contract_id = 'SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.amm-swap-pool-v1-1'

[contracts.test]
path = 'contracts/test.clar'
clarity_version = 2
epoch = 2.1
```
**Expected behavior**

Throw an error that the epoch in clarinet.toml is wrong.

**Comment by hugocaillard** [comment]
@LakshmiLavanyaKasturi 
I think that we can bring some clarification about this issue in the doc but there's also a change to do at the code level to throw a better error

**Comment by Rapha-btc** [comment]
The solution: have requirements input 'latest' or remove that field altogether. 3 devs have fallen in this time consuming bug that i know of fyi.

**Comment by hugoclrd** [comment]
@Rapha-btc

> have requirements input 'latest' or remove that field altogether

As discussed in #1965, the epoch of a requirement isn't specified in the manifest. The correct way to add requirements is as follow:
```toml
[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'
```

Clarinet will **automatically** use the real epoch of the contract.

This issue is still very relevant, but setting your **contract** to `"latest"` epoch does mitigate it (see #1963) 
```toml
[contracts.counter]
path = 'contracts/counter.clar'
clarity_version = 3
epoch = 'latest'
```
