### ISSUE TITLE
Clarity Version undefined while deployment says 2

### ISSUE THREAD

**Issue by friedger** [hirosystems/clarinet#1137]
**Describe the bug**
Clarity version used in a deployment is not written to the chain

**To Reproduce**
1. Apply the following deployment:
``` 
---
id: 0
name: Mainnet deployment
network: mainnet
stacks-node: "https://api.hiro.so"
bitcoin-node: "http://blockstack:blockstacksystem@bitcoin.blockstack.com:8332"
plan:
  batches:
    - id: 0
      transactions:
        - contract-publish:
            contract-name: fp-payout-1
            expected-sender: SP21YTSM60CAY6D011EZVEVNKXVW8FVZE198XEFFP
            cost: 20000
            path: contracts/payout/payout-self-service.clar
            anchor-block-only: true
            clarity-version: 2
``` 
2. See that the clarity-version is undefined

**Expected behavior**
clarity-version should be 2

https://api.hiro.so/extended/v1/tx/0x8d51044024c60b4684f93514ebfbeba2c7b277cd2fc449b69ef2ff1e4c8c24ae

![image](https://github.com/hirosystems/clarinet/assets/1449049/5c50bd4d-5b9b-4933-89d7-3111be94f4d3)

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Environment (please complete the following information):**
 - OS (version): [e.g. macOS (13.4.1)]
 - Docker version [e.g. 24.0.4]
 - Clarinet version [e.g. 1.7.0] - Please use the latest version

**Additional context**
Add any other context about the problem here:
