### ISSUE TITLE
VSCode extension should warn if there an error in Clarinet.toml

### ISSUE THREAD

**Issue by hugocaillard** [hirosystems/clarinet#1440]
## Problem

If the manifest (clarinet.toml) is invalid, the VSCode extension will silently fail.
It can be reproduced with an invalid manifest like so

```toml
[contracts.contract]
path = 'contracts/traits/contract.clar'
clarity_version = 2
epoch = 2.4
clarity_version = 2
epoch = 2.4
```

## Fix

Show an error popup in vscode
