### ISSUE TITLE
Allow to load custom boot contracts

### ISSUE THREAD

**Issue by hugocaillard** [hirosystems/clarinet#1449]
## Context

Clarinet embeds a copy of the boot contracts.
For stacks core developers, it would be useful to have the ability to load custom code instead.

## Solution

Add on options to override boot contracts sources.
In the Clarinet.toml, it should be possible to specify the path to the source file of a boot contract.
This code would be used in place of the one embedded in clarinet. It could also be used to get the code coverage and therefore remove the need for https://github.com/hirosystems/clarinet/pull/1412, and achieve the same result in a more elegant way

```toml
[override_boot_contracts_source]
pox-4 = "./custom-boot-contracts/pox-4.clar"
```
