### ISSUE TITLE
How to pass in the default.testnet-plan.yaml - list 5 (optional principal) parameter

### ISSUE THREAD

**Issue by jovanvuleta** [hirosystems/clarinet#1479]
How is list of optionals passed in the testnet deployment plan? - list 5 (optional principal) parameter

```
(define-public (initialize-governance (governance-multisigs (list 5 (optional principal))))
  (begin
    (asserts! (not (var-get governance-initialized)) ERR-CONTRACT-ALREADY-INITIALIZED)
    (try! (is-contract-deployer))
    (var-set governance-initialized true)
    (map set-governance-multisig governance-multisigs)
    SUCCESS
  )
)
```

Example:
```
          - contract-call:
                contract-id: ST2CY5V39NHDPWSXMW9QDT3HC3GD6Q6XX4CFRK9AG.governance
                expected-sender: ST2CY5V39NHDPWSXMW9QDT3HC3GD6Q6XX4CFRK9AG
                method: initialize-governance
                parameters:
                    - "'ST2CY5V39NHDPWSXMW9QDT3HC3GD6Q6XX4CFRK9AG none none none none"
                cost: 10800
```
