### ISSUE TITLE
[Feature] Clarinet github action

### ISSUE THREAD

**Issue by pradel** [hirosystems/clarinet#171]
When integrating clarinet into the github action CI, one need to install clarinet manually. It would be really sweet to have a github action to install clarinet easily, as an inspiration for how pnpm is doing it could be done like this:

```yaml
jobs:
  test-contracts:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: contracts

    steps:
      - uses: actions/checkout@v2

      - uses: hirosystems/clarinetaction-setup@v1
         with:
           version: 0.19.1

      - name: Test contracts
        run: clarinet test
``` 

This is how I do it at the moment in one of my repo.

```yaml
jobs:
  test-contracts:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: contracts

    steps:
      - uses: actions/checkout@v2

      - name: Install clarinet
        run: |
          wget -L https://github.com/hirosystems/clarinet/releases/download/v0.19.1/clarinet-linux-x64.tar.gz
          tar xzf clarinet-linux-x64.tar.gz
          chmod +x ./clarinet
          mkdir -p "$HOME/.local/bin"
          mv ./clarinet "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Test contracts
        run: clarinet test
```
