### ISSUE TITLE
`error: use of unresolved contract` when already defined

### ISSUE THREAD

**Issue by whoabuddy** [hirosystems/clarinet#311]
I am working on a "tardis" contract that retrieves historical information for MIA/NYC functions using `at-block`, and ran into this error when trying to set up a check for these mainnet contracts.

The main directory for contracts in the branch is here:
https://github.com/citycoins/citycoin/tree/feat/add-sip012-style-vote/contracts

The tardis contract that is used in testing:
https://github.com/citycoins/citycoin/blob/feat/add-sip012-style-vote/contracts/citycoin-tardis-v2.clar

The tardis contract that will be deployed to mainnet:
https://github.com/citycoins/citycoin/blob/feat/add-sip012-style-vote/contracts/Tardis/citycoin-tardis-v2-mainnet.clar

Currently our test structure is setup with a bash script to prepare the tests as part of `clarinet:prepare`, and executes the following steps:

1. copies all contract files from `./contracts` to `./contracts/clarinet`
2. modifies address used in impl-trait by replacing it with a different address. e.g.
   `(impl-trait 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-10-ft-standard.ft-trait)`
   is converted to:
   `(impl-trait 'ST1HTBVD3JG9C05J7HBJTHGR0GGW7KXW28M5JS8QE.sip-10-ft-standard.ft-trait)`
3. appends code stored in `./contracts/test_addons` at the end of contract file with the same name
   e.g. `./contracts/test_addons/citycoin-core-v1.clar` is added to `./contracts/citycoin-core-v1.clar`

We want to keep this structure in place, but by default anything placed in a subfolder is not copied or tested because we've had issues with getting the appropriate external contracts recognized. This means the following files aren't passed to `clarinet check`:

- MiamiCoin/auth.clar
- MiamiCoin/core-v1.clar
- MiamiCoin/token.clar
- NewYorkCityCoin/auth.clar
- NewYorkCityCoin/core-v1.clar
- NewYorkCityCoin/token.clar
- Tardis/citycoin-tardis-v1-mainnet.clar
- Tardis/citycoin-tardis-v2-mainnet.clar

**What we would like to do** is make it so that the contracts listed above could be listed in the Clarinet.toml and checked through `clarinet check`, and attempted this using the `project.requirements` setting seen in other projects.

The updated Clarinet.toml settings are below starting with the Tardis contract:

```toml
[project]
name = "citycoin"

[[project.requirements]]
contract_id = "SP466FNC0P7JWTNM2R9T199QRZN1MYEDTAR0KP27.miamicoin-auth"
[[project.requirements]]
contract_id = "SP466FNC0P7JWTNM2R9T199QRZN1MYEDTAR0KP27.miamicoin-core-v1"
[[project.requirements]]
contract_id = "SP466FNC0P7JWTNM2R9T199QRZN1MYEDTAR0KP27.miamicoin-token"

[[project.requirements]]
contract_id = "SP2H8PY27SEZ03MWRKS5XABZYQN17ETGQS3527SA5.newyorkcitycoin-auth"
[[project.requirements]]
contract_id = "SP2H8PY27SEZ03MWRKS5XABZYQN17ETGQS3527SA5.newyorkcitycoin-core-v1"
[[project.requirements]]
contract_id = "SP2H8PY27SEZ03MWRKS5XABZYQN17ETGQS3527SA5.newyorkcitycoin-token"

[contracts.citycoin-vrf]
path = "contracts/clarinet/citycoin-vrf.clar"
depends_on = []

[contracts.citycoin-core-trait]
path = "contracts/clarinet/citycoin-core-trait.clar"
depends_on = []

[contracts.citycoin-token-trait]
path = "contracts/clarinet/citycoin-token-trait.clar"
depends_on = []

[contracts.citycoin-auth]
path = "contracts/clarinet/citycoin-auth.clar"
depends_on = ["citycoin-core-trait", "citycoin-token-trait"]

[contracts.citycoin-token]
path = "contracts/clarinet/citycoin-token.clar"
depends_on = ["sip-010-trait", "citycoin-auth", "citycoin-token-trait"]

[contracts.citycoin-core-v1]
path = "contracts/clarinet/citycoin-core-v1.clar"
depends_on = ["citycoin-auth", "citycoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.citycoin-vote-v1]
path = "contracts/clarinet/citycoin-vote-v1.clar"
depends_on = ["citycoin-core-v1"]

[contracts.citycoin-tardis-v1]
path = "contracts/clarinet/citycoin-tardis-v1.clar"
depends_on = ["citycoin-core-v1"]

[contracts.citycoin-tardis-v2]
path = "contracts/clarinet/citycoin-tardis-v2.clar"
depends_on = ["citycoin-core-v1"]

# contracts listed below are mainnet deployments
# and added only to ensure clarinet check passes

[contracts.citycoin-tardis-v1-mainnet]
path = "contracts/Tardis/citycoin-tardis-v1-mainnet.clar"
depends_on = []

# contracts listed below are used only in test suite

[contracts.citycoin-core-v2]
path = "contracts/clarinet/citycoin-core-v2.clar"
depends_on = ["citycoin-auth", "citycoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.sip-010-trait]
path = "contracts/clarinet/sip-10-ft-standard.clar"
depends_on = []

[contracts.test-utils]
path = "contracts/clarinet/test-utils.clar"
depends_on = ["citycoin-core-v1"]
```

This removes most of the errors from the tardis contract, but the same error still comes up due to references in the required contracts to each other, specifically:

```
miamicoin-core-v1:807:4: error: use of unresolved contract 'SP466FNC0P7JWTNM2R9T199QRZN1MYEDTAR0KP27.miamicoin-token'
  (let
   ^~~
  miamicoin-core-v1:808:5:
    (
      (coinbaseAmounts (try! (contract-call? 'SP466FNC0P7JWTNM2R9T199QRZN1MYEDTAR0KP27.miamicoin-token get-coinbase-thresholds)))
    ^
  miamicoin-core-v1:811:5:
    (var-set coinbaseThreshold1 (get coinbaseThreshold1 coinbaseAmounts))
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  miamicoin-core-v1:812:5:
    (var-set coinbaseThreshold2 (get coinbaseThreshold2 coinbaseAmounts))
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  miamicoin-core-v1:813:5:
    (var-set coinbaseThreshold3 (get coinbaseThreshold3 coinbaseAmounts))
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  miamicoin-core-v1:814:5:
    (var-set coinbaseThreshold4 (get coinbaseThreshold4 coinbaseAmounts))
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  miamicoin-core-v1:815:5:
    (var-set coinbaseThreshold5 (get coinbaseThreshold5 coinbaseAmounts))
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  miamicoin-core-v1:816:5:
    (ok true)
    ^~~~~~~~~
newyorkcitycoin-core-v1:816:4: error: use of unresolved contract 'SP2H8PY27SEZ03MWRKS5XABZYQN17ETGQS3527SA5.newyorkcitycoin-token'
  (let
   ^~~
  newyorkcitycoin-core-v1:817:5:
    (
      (coinbaseAmounts (try! (contract-call? 'SP2H8PY27SEZ03MWRKS5XABZYQN17ETGQS3527SA5.newyorkcitycoin-token get-coinbase-thresholds)))
    ^
  newyorkcitycoin-core-v1:820:5:
    (var-set coinbaseThreshold1 (get coinbaseThreshold1 coinbaseAmounts))
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  newyorkcitycoin-core-v1:821:5:
    (var-set coinbaseThreshold2 (get coinbaseThreshold2 coinbaseAmounts))
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  newyorkcitycoin-core-v1:822:5:
    (var-set coinbaseThreshold3 (get coinbaseThreshold3 coinbaseAmounts))
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  newyorkcitycoin-core-v1:823:5:
    (var-set coinbaseThreshold4 (get coinbaseThreshold4 coinbaseAmounts))
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  newyorkcitycoin-core-v1:824:5:
    (var-set coinbaseThreshold5 (get coinbaseThreshold5 coinbaseAmounts))
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  newyorkcitycoin-core-v1:825:5:
    (ok true)
    ^~~~~~~~~
```

Following that is an error in the tardis contract referencing one of the required contracts:

```
tardis-v1:65:4: error: use of unresolved contract 'SP466FNC0P7JWTNM2R9T199QRZN1MYEDTAR0KP27.miamicoin-core-v1'
  (let
   ^~~
  tardis-v1:66:5:
    (
      (blockHash (unwrap! (get-block-hash blockHeight) (err ERR_INVALID_BLOCK)))
      (cycleId (unwrap! (contract-call? 'SP466FNC0P7JWTNM2R9T199QRZN1MYEDTAR0KP27.miamicoin-core-v1 get-reward-cycle blockHeight) (err ERR_CYCLE_NOT_FOUND)))
      (stats (unwrap! (at-block blockHash (contract-call? 'SP466FNC0P7JWTNM2R9T199QRZN1MYEDTAR0KP27.miamicoin-core-v1 get-stacking-stats-at-cycle cycleId)) (err ERR_CYCLE_NOT_FOUND)))
    ^
  tardis-v1:71:5:
    (ok stats)
    ^~~~~~~~~~
```

It feels like I'm missing something simple here, any help is appreciated!

**Comment by obycode** [comment]
https://github.com/hirosystems/clarity-repl/pull/118 improves the dependency detection and makes some changes to the requirements support. I am in the middle of testing it now. Based on your description, it looks like we may need to use the dependency detector to order the requirements before loading them. I will investigate that. In the meantime, the branch that you referenced originally is no longer there. Can you recommend an easy way to reproduce your issue?

**Comment by obycode** [comment]
Using the main branch and your modified Clarinet.toml file, I reproduced the problem. If you use https://github.com/hirosystems/clarity-repl/pull/118, for now, you can manually reorder your requirements and it works.

```toml
[[project.requirements]]
contract_id = "SP466FNC0P7JWTNM2R9T199QRZN1MYEDTAR0KP27.miamicoin-auth"
[[project.requirements]]
contract_id = "SP466FNC0P7JWTNM2R9T199QRZN1MYEDTAR0KP27.miamicoin-token"
[[project.requirements]]
contract_id = "SP466FNC0P7JWTNM2R9T199QRZN1MYEDTAR0KP27.miamicoin-core-v1"
[[project.requirements]]
contract_id = "SP2H8PY27SEZ03MWRKS5XABZYQN17ETGQS3527SA5.newyorkcitycoin-auth"
[[project.requirements]]
contract_id = "SP2H8PY27SEZ03MWRKS5XABZYQN17ETGQS3527SA5.newyorkcitycoin-token"
[[project.requirements]]
contract_id = "SP2H8PY27SEZ03MWRKS5XABZYQN17ETGQS3527SA5.newyorkcitycoin-core-v1"
```

We should be able to use the same logic to automatically order these for you as well, but that is not in place yet.

**Comment by whoabuddy** [comment]
Hi @obycode that's great news! The branch in question was merged to main however the requirements were left out since it wasn't functioning correctly. Thanks for figuring that out to reproduce.

It sounds like this will work great for what we need and I look forward to testing it out!

**Comment by whoabuddy** [comment]
I gave this a try this morning and it was unsuccessful, here are the steps I took:

1. Cloned the `clarity-repl` repository
2. Checked out the `feat/improved-dependency-checker` branch
3. Ran `cargo install --bin clarity-repl --path .`
4. Added the requirements above and `tardis-v1-mainnet` path in Clarinet.toml
5. Attempted to run `npm run clarinet:check` in the contracts directory
*(that npm command executes the prepare script before running check)*
6. Panicked with `ERROR: Clarity VM attempted GET on non-nested context.`

The verbose backtrace is below - hopefully it's something simple! This feature would make our testing much easier and more reliable for mainnet versions :slightly_smiling_face: 

```
~/Dev/citycoins/contracts$ RUST_BACKTRACE=full clarinet check

thread 'main' panicked at 'ERROR: Clarity VM attempted GET on non-nested context.', /home/whoabuddy/.cargo/registry/src/github.com-1ecc6299db9ec823/clarity-repl-0.24.0/src/clarity/database/key_value_wrapper.rs:396:14
stack backtrace:
   0:     0x559c7b622c3c - std::backtrace_rs::backtrace::libunwind::trace::h09f7e4e089375279
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x559c7b622c3c - std::backtrace_rs::backtrace::trace_unsynchronized::h1ec96f1c7087094e
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x559c7b622c3c - std::sys_common::backtrace::_print_fmt::h317b71fc9a5cf964
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x559c7b622c3c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he3555b48e7dfe7f0
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x559c7b64cf9c - core::fmt::write::h513b07ca38f4fb1b
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/fmt/mod.rs:1149:17
   5:     0x559c7b618e85 - std::io::Write::write_fmt::haf8c932b52111354
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/io/mod.rs:1697:15
   6:     0x559c7b624950 - std::sys_common::backtrace::_print::h195c38364780a303
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x559c7b624950 - std::sys_common::backtrace::print::hc09dfdea923b6730
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x559c7b624950 - std::panicking::default_hook::{{closure}}::hb2e38ec0d91046a3
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:211:50
   9:     0x559c7b624505 - std::panicking::default_hook::h60284635b0ad54a8
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:228:9
  10:     0x559c7b625004 - std::panicking::rust_panic_with_hook::ha677a669fb275654
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:606:17
  11:     0x559c7b624ae0 - std::panicking::begin_panic_handler::{{closure}}::h976246fb95d93c31
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:502:13
  12:     0x559c7b6230e4 - std::sys_common::backtrace::__rust_end_short_backtrace::h38077ee5b7b9f99a
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x559c7b624a49 - rust_begin_unwind
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
  14:     0x559c78d67ac1 - core::panicking::panic_fmt::h35f3a62252ba0fd2
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
  15:     0x559c7b64ae71 - core::panicking::panic_display::h571c717fc6a00c7d
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:63:5
  16:     0x559c78d679bb - core::option::expect_failed::h5f4cab7748df5501
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/option.rs:1637:5
  17:     0x559c7b037962 - clarity_repl::clarity::database::key_value_wrapper::RollbackWrapper::get_metadata::h016f5571e5e0db2b
  18:     0x559c7b1434a5 - clarity_repl::clarity::analysis::analysis_db::AnalysisDatabase::load_contract::h9f354f84f16fa1d6
  19:     0x559c7b143f9b - clarity_repl::clarity::analysis::analysis_db::AnalysisDatabase::get_defined_trait::h4fc86fa35034db5a
  20:     0x559c7afca3b3 - <clarity_repl::analysis::dependency_detector::DependencyDetector as clarity_repl::analysis::ast_visitor::ASTVisitor>::visit_dynamic_contract_call::hc8cfcb51a00cf623
  21:     0x559c7afc7f38 - clarity_repl::analysis::ast_visitor::ASTVisitor::traverse_list::hbaa486e682b01e1b
  22:     0x559c7afc7d67 - clarity_repl::analysis::ast_visitor::ASTVisitor::traverse_list::hbaa486e682b01e1b
  23:     0x559c7afc9649 - <clarity_repl::analysis::dependency_detector::DependencyDetector as clarity_repl::analysis::ast_visitor::ASTVisitor>::traverse_define_public::hc7494ec3bb015a9e
  24:     0x559c7afc75af - clarity_repl::analysis::ast_visitor::ASTVisitor::traverse_list::hbaa486e682b01e1b
  25:     0x559c7afcad83 - <clarity_repl::analysis::dependency_detector::DependencyDetector as clarity_repl::analysis::AnalysisPass>::run_pass::h4dd23d0bc4054ba6
  26:     0x559c7afb80cf - clarity_repl::repl::interpreter::ClarityInterpreter::detect_dependencies::h3ed9cff830fcafd5
  27:     0x559c7afeb7ec - clarity_repl::repl::session::Session::resolve_link::h48e58e034511cb20
  28:     0x559c7afedda7 - clarity_repl::repl::session::Session::interpret_initial_contracts::hfafd53ffd98fd384
  29:     0x559c7afed21d - clarity_repl::repl::session::Session::start::h15ea55468c207e42
  30:     0x559c78f66dac - clarinet::poke::load_session::h4fe784584a6cb361
  31:     0x559c78e8205c - clarinet::frontend::cli::main::h93845024adc0d620
  32:     0x559c790525f3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h29e9b81d99b31667
  33:     0x559c790b6b99 - std::rt::lang_start::{{closure}}::ha9b1542684b7b497
  34:     0x559c7b6228cb - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h7e688d7cdfeb7e00
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:259:13
  35:     0x559c7b6228cb - std::panicking::try::do_call::h4be824d2350b44c9
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
  36:     0x559c7b6228cb - std::panicking::try::h0a6fc7affbe5088d
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
  37:     0x559c7b6228cb - std::panic::catch_unwind::h22c320f732ec805e
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
  38:     0x559c7b6228cb - std::rt::lang_start_internal::{{closure}}::hd38309c108fe679d
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:128:48
  39:     0x559c7b6228cb - std::panicking::try::do_call::h8fcaf501f097a28e
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
  40:     0x559c7b6228cb - std::panicking::try::h20e906825f98acc1
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
  41:     0x559c7b6228cb - std::panic::catch_unwind::h8c5234dc632124ef
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
  42:     0x559c7b6228cb - std::rt::lang_start_internal::hc4dd8cd3ec4518c2
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:128:20
  43:     0x559c78f6a9e2 - main
  44:     0x7f766ded50b3 - __libc_start_main
  45:     0x559c78d6884e - _start
  46:                0x0 - <unknown>
```

I was working on some other changes so won't be saving it to this branch, but if you need a separate version that incorporates the changes that caused the error, or any other info let me know!

**Comment by obycode** [comment]
Thanks for trying it out and for the detailed steps @whoabuddy. I think this should be something simple. Clarinet actually links with clarity-repl as a library, it does not use an installed binary, so to test it you'll want to also checkout clarinet, modify Cargo.toml to use your local copy of clarity-repl, then build and install clarinet.

Complete steps:
```sh
git clone git@github.com:hirosystems/clarity-repl.git
cd clarity-repl
git checkout feat/improved-dependency-checker
cd ../
git checkout git@github.com:hirosystems/clarinet.git
cd clarinet
# modify Cargo.toml
# -# clarity_repl = { package = "clarity-repl", path = "../../clarity-repl", features = ["cli"] }
# -clarity_repl = { package = "clarity-repl", version = "=0.25.0" }
# +clarity_repl = { package = "clarity-repl", path = "../clarity-repl", features = ["cli"] }
# +# clarity_repl = { package = "clarity-repl", version = "=0.25.0" }
cargo install --path .
```

I tried running your script with `npm run clarinet:check` and after some modifications to make it work on Mac, it finishes successfully.

**Comment by obycode** [comment]
Hi @whoabuddy. Can you try out the newly released clarinet 0.29.0 and let me know if it fixes the problem for you?

**Comment by whoabuddy** [comment]
Hi @obycode I installed v0.29.0 and tested it out, now I'm getting an error with the toml file:

```
$ clarinet --version
clarinet 0.29.0
```

Error:

```
Error: there is an issue with the Clarinet.toml file
Error { inner: ErrorInner { kind: Custom, line: Some(130), col: 0, at: Some(4405), message: "duplicate field `requirements`", key: ["project"] } }
```

TOML file:

```toml
[project]
name = "citycoin"
requirements = []

[repl.analysis]
costs_version = 2

# mainnet contract references

[[project.requirements]]
contract_id = "SP466FNC0P7JWTNM2R9T199QRZN1MYEDTAR0KP27.miamicoin-auth"
[[project.requirements]]
contract_id = "SP466FNC0P7JWTNM2R9T199QRZN1MYEDTAR0KP27.miamicoin-core-v1"
[[project.requirements]]
contract_id = "SP466FNC0P7JWTNM2R9T199QRZN1MYEDTAR0KP27.miamicoin-token"

[[project.requirements]]
contract_id = "SP2H8PY27SEZ03MWRKS5XABZYQN17ETGQS3527SA5.newyorkcitycoin-auth"
[[project.requirements]]
contract_id = "SP2H8PY27SEZ03MWRKS5XABZYQN17ETGQS3527SA5.newyorkcitycoin-core-v1"
[[project.requirements]]
contract_id = "SP2H8PY27SEZ03MWRKS5XABZYQN17ETGQS3527SA5.newyorkcitycoin-token"

# contracts listed below are already deployed
# and added only to ensure clarinet check passes

[contracts.citycoin-tardis-v1-mainnet]
path = "contracts/Tardis/citycoin-tardis-v1-mainnet.clar"
depends_on = []

# all contracts below are used with the testing suite

# mia

[contracts.miamicoin-auth]
path = "contracts/cities/mia/local/miamicoin-auth.clar"
depends_on = ["citycoin-core-trait", "citycoin-token-trait"]

[contracts.miamicoin-core-v1]
path = "contracts/cities/mia/local/miamicoin-core-v1.clar"
depends_on = ["miamicoin-auth", "miamicoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.miamicoin-core-v2]
path = "contracts/cities/mia/local/miamicoin-core-v1.clar"
depends_on = ["miamicoin-auth", "miamicoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.miamicoin-core-v3]
path = "contracts/cities/mia/local/miamicoin-core-v1.clar"
depends_on = ["miamicoin-auth", "miamicoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.miamicoin-token]
path = "contracts/cities/mia/local/miamicoin-token.clar"
depends_on = ["sip-010-trait-ft-standard", "miamicoin-auth", "citycoin-token-trait"]

# nyc

[contracts.newyorkcitycoin-auth]
path = "contracts/cities/nyc/local/newyorkcitycoin-auth.clar"
depends_on = ["citycoin-core-trait", "citycoin-token-trait"]

[contracts.newyorkcitycoin-core-v1]
path = "contracts/cities/nyc/local/newyorkcitycoin-core-v1.clar"
depends_on = ["newyorkcitycoin-auth", "newyorkcitycoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.newyorkcitycoin-core-v2]
path = "contracts/cities/nyc/local/newyorkcitycoin-core-v1.clar"
depends_on = ["newyorkcitycoin-auth", "newyorkcitycoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.newyorkcitycoin-core-v3]
path = "contracts/cities/nyc/local/newyorkcitycoin-core-v1.clar"
depends_on = ["newyorkcitycoin-auth", "newyorkcitycoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.newyorkcitycoin-token]
path = "contracts/cities/nyc/local/newyorkcitycoin-token.clar"
depends_on = ["sip-010-trait-ft-standard", "newyorkcitycoin-auth", "citycoin-token-trait"]

# core

[contracts.citycoin-core-trait]
path = "contracts/core/local/citycoin-core-trait.clar"
depends_on = []

[contracts.citycoin-token-trait]
path = "contracts/core/local/citycoin-token-trait.clar"
depends_on = []

[contracts.citycoin-auth]
path = "contracts/core/local/citycoin-auth.clar"
depends_on = ["citycoin-core-trait", "citycoin-token-trait"]

[contracts.citycoin-token]
path = "contracts/core/local/citycoin-token.clar"
depends_on = ["sip-010-trait-ft-standard", "citycoin-auth", "citycoin-token-trait"]

[contracts.citycoin-core-v1]
path = "contracts/core/local/citycoin-core-v1.clar"
depends_on = ["citycoin-auth", "citycoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.citycoin-core-v2]
path = "contracts/core/local/citycoin-core-v2.clar"
depends_on = ["citycoin-auth", "citycoin-token", "citycoin-vrf", "citycoin-core-trait"]

[contracts.citycoin-core-v3]
path = "contracts/core/local/citycoin-core-v2.clar"
depends_on = ["citycoin-auth", "citycoin-token", "citycoin-vrf", "citycoin-core-trait"]

# tardis

[contracts.citycoin-tardis-v1]
path = "contracts/tardis/local/citycoin-tardis-v1.clar"
depends_on = ["citycoin-core-v1"]

[contracts.citycoin-tardis-v2]
path = "contracts/tardis/local/citycoin-tardis-v2.clar"
depends_on = ["citycoin-core-v1"]

# utilities

[contracts.sip-010-trait-ft-standard]
path = "contracts/utilities/local/sip-010-trait-ft-standard.clar"
depends_on = []

[contracts.test-utils]
path = "contracts/utilities/local/test-utils.clar"
depends_on = ["citycoin-core-v1"]

# vote

[contracts.citycoin-vote-v1]
path = "contracts/vote/local/citycoin-vote-v1.clar"
depends_on = ["citycoin-core-v1"]

# vrf

[contracts.citycoin-vrf]
path = "contracts/vrf/local/citycoin-vrf.clar"
depends_on = []
```

**Comment by lgalabru** [comment]
@whoabuddy in your toml file, can you try to remove this line:

```toml
[project]
...
requirements = []
```
