### ISSUE TITLE
Getting invalid `use of unresolved contract` in LSP

### ISSUE THREAD

**Issue by obycode** [hirosystems/clarinet#394]
When using a trait from a contract specified in the `requirements`, `clarinet check` is successful, but the LSP displays an error: `use of unresolved contract`.

_contracts/bug.clar_:
```clarity
(use-trait nft-trait 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait.nft-trait)
42 ;; this is here to avoid https://github.com/hirosystems/clarity-repl/issues/109
```

_Clarinet.toml_:
```toml
[project]
name = "check-required"

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait"

[contracts.bug]
path = "contracts/bug.clar"
```
