### ISSUE TITLE
Don't count `requirements` in "contracts checked" count

### ISSUE THREAD

**Issue by obycode** [hirosystems/clarinet#395]
`clarinet check` reports the number of contracts checked, e.g.:

```
✔ 2 contracts checked
```

This number should not include contracts from `requirements`.

Using the same project from #394 (below), this should show 1 contract checked, but it reports 2.

_contracts/bug.clar_:
```clarity
(use-trait nft-trait 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait.nft-trait)
42 ;; this is here to avoid https://github.com/hirosystems/clarity-repl/issues/109
```

_Clarinet.toml_:
```toml
[project]
name = "check-required"

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait"

[contracts.bug]
path = "contracts/bug.clar"
```
