### ISSUE TITLE
Adding the Option to Advance Tip Height to the deployment plan. 

### ISSUE THREAD

**Issue by FriendsFerdinand** [hirosystems/clarinet#548]
Currently, it is only possible to advance the block height in a deployment plan by sending an empty list of transactions, like so:

```
    - id: 1
      transactions: []
```

However, this only advances the tip height by 1 block. It might be required to advance the height of the blockchain by more that 1 and to do so one would have to copy the above command multiple times.

So, something like this:

```
- id: 1
      transactions:
        - advance-tip-height:
            blocks: 10
```

To advance the tip height by 10 blocks.
