### ISSUE TITLE
LSP: Contracts can be analysed multiple times

### ISSUE THREAD

**Issue by hugocaillard** [hirosystems/clarinet#556]
It's possible to declare multiple contracts identifiers with the same source file in the Clarinet.toml

```toml
[contracts.counter-1]
path = "contracts/counter.clar"

[contracts.counter-2]
path = "contracts/counter.clar"
```

In this case, the "manifest.contracts" will have twice the same source code, and we'll compute the analysis twice.
https://github.com/hirosystems/clarinet/blob/ed323ec4edbb70647fec5a0040b83d0c95ca81d3/components/clarinet-deployments/src/lib.rs#L497

It leads to some performances issues, for instance, here the `.get()` should be replaces with `.remove()` to avoid `.clone()`

### Potential solutions
- emit an error if a path is used multiple times in a manifest
- rework the iteration to avoid analyzing twice the same source
