### ISSUE TITLE
Pre-populate devnet.toml with Stacks 2.1-related options/flags

### ISSUE THREAD

**Issue by mefrem** [hirosystems/clarinet#715]
It would help the developer to know they can enable 2.1 features, including specific 2.1-associated Clarity contracts, specifying epoch changes to your devnet by Stacks block, with flags in the `Devnet.toml` file. Can these be included by default?

```toml
enable_next_features = true
epoch_2_0 = 103
epoch_2_05 = 104
epoch_2_1 = 106
pox_2_activation = 109
```
